# Generated by Django 3.0.8 on 2020-09-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='imageproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.Comment'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.Imageproduct'),
        ),
    ]
