# Generated by Django 3.0.8 on 2020-09-03 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=30, null=True)),
                ('cart', models.CharField(blank=True, max_length=30, null=True)),
                ('number_product', models.CharField(blank=True, max_length=30, null=True)),
                ('total_price', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Middle_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.IntegerField()),
                ('cart', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='middle_cart', to='finance.Cart')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
