# Generated by Django 3.0.8 on 2020-09-19 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200903_1104'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middle_cart',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='middle_cart', to='product.Product'),
        ),
    ]
